v2.20.28.2 (1.fixed [Render thread/ERROR]: Parsing error loading recipe pokey_and_alexs_mod:tungsten_ore_block_recipe com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:deleted_mod_element' (done?)
2.fixed [Render thread/ERROR]: Parsing error loading recipe pokey_and_alexs_mod:luminisomtoingot
com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:luminisom_armor_helmet' (done?)

3.fixed Parsing error loading recipe pokey_and_alexs_mod:ricebowlrecipe
com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs__mc_mod:rice'

4.fixed [Render thread/ERROR]: Parsing error loading recipe pokey_and_alexs_mod:luminisomtoingotboots
com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:luminisom_armor_boots' (done?)

5.removed rice and crafting recipes for it

6.fix java.lang.IllegalStateException: Item: pokey_and_alexs_mod:deleted_mod_element does not exist

7.fix com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:tungsten_ingot'

8.fixed [Render thread/ERROR]: Parsing error loading recipe pokey_and_alexs_mod:thornreethtocharcoal
com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:deleted_mod_element_helmet'

9.fixed [Render thread/ERROR]: Parsing error loading recipe pokey_and_alexs_mod:reinforcedtungsteningottobock
com.google.gson.JsonSyntaxException: Unknown item 'pokey_and_alexs_mod:deleted_mod_element')